### PR TITLE
add basic sample template for client connection

### PR DESCRIPTION
**Pull request by tz70s**
I add a basic template for client side, we can execute the main classes in `broke-sample` as client side entry point. 

You can implement based on this template for client connection, a.k.a `BlockClient.java.`

@allenlee820202 please review this, thanks!

### CODE REVIEW

**Comment by tz70s** [comment]
Yep, I think I already did this.

**Comment by allenlee820202** [comment]
But I saw that the SamplePublish.java is under the root directory, is that correct?

**Comment by allenlee820202** [comment]
Oh I got it, that's my fault.

**Comment by tz70s** [comment]
Thanks!

**Pull request merged**
